= Construction d’un projet
// https://fr.wikipedia.org/wiki/Moteur_de_production

== Implémentation et distribution
* Pour la plupart des langages, plusieurs _implémentations_ sont disponibles
** certaines sont généralistes
** d'autres sont spécialisées pour un type particulier de situation
* De même, pour plus de simplicité d'usage, les langages sont proposées sous la forme d'une _distribution_
* Une distribution va regrouper une implémentation du langage avec les bibliothèques standards ainsi que des outils de développement

.Implémentations par langage
[%header]
|===
| Java | Python

| http://openjdk.java.net/groups/hotspot/[HotSpot] (http://openjdk.java.net/[OpenJdk]),
https://www.eclipse.org/openj9/[OpenJ9] (https://www.eclipse.org/[Eclipse]),
https://www.graalvm.org/[GraalVM]
| https://fr.wikipedia.org/wiki/CPython[CPython],
http://www.jython.org/[Jython],
http://ironpython.net/[IronPython],
http://pypy.org/[PyPy]

|===

.Distributions par langage
[%header]
|===
| Java | Python

| http://openjdk.java.net/[OpenJdk]/ https://adoptopenjdk.net/[AdoptOpenJDK],
http://www.oracle.com/technetwork/java/javase/downloads/index.html[Oracle Java SE],
https://www.microsoft.com/openjdk[Microsoft Build of OpenJDK]
| https://www.python.org/downloads/[Distribution de référence],
https://www.continuum.io/anaconda-overview[Anaconda]

|===

== Automatisation du __build__ (icon:wikipedia-w[link="https://en.wikipedia.org/wiki/Build_automation"])
* La gestion de la compilation (\emph{Build automation}) consiste à automatiser les tâches répétitives des développeurs
** compilation (mode normal, mode débogage, \dots)
** génération de la version de distribution
** génération de la documentation et des notes de version
** lancement des tests
** déploiement
* Ces tâches sont alors réalisées plus efficacement et moins sujettes aux erreurs
** évite les fastidieuses lignes de commande
** permet une compilation \og intelligente\fg{}
** rend le processus reproductible
* Peut être déclenché
+
à la demande:: l'utilisateur exécute un script
par un ordonnanceur:: exécuté à un instant donné
par un événement:: provoqué par un événement particulier

.Outils de build par langage
[%header]
|===
| Java/Scala | C/C++ | Autres

| https://gradle.org/[Gradle],
https://maven.apache.org/[Maven],
http://ant.apache.org[Ant],
http://www.scala-sbt.org/[sbt]
| http://www.gnu.org/software/make[Make],
https://cmake.org/[CMake]
| http://docs.seattlerb.org/rake/[Rake],
https://waf.io/[Waf],
http://www.scons.org/[SCons]

|===
